// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../../android/content/Context.dart' as context$_;

import '../JIpConfiguration.dart' as jipconfiguration$_;

/// from: `dev.zeekr.connectivity.ethernet.JEthernetManager$Companion`
class JEthernetManager$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JEthernetManager$Companion> $type;

  @jni$_.internal
  JEthernetManager$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/ethernet/JEthernetManager$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$Companion?> nullableType =
      $JEthernetManager$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$Companion> type =
      $JEthernetManager$Companion$Type$();
  static final _id_getETHERNET_SERVICE = _class.instanceMethodId(
    r'getETHERNET_SERVICE',
    r'()Ljava/lang/String;',
  );

  static final _getETHERNET_SERVICE =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getETHERNET_SERVICE()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString getETHERNET_SERVICE() {
    return _getETHERNET_SERVICE(
      reference.pointer,
      _id_getETHERNET_SERVICE as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<?> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JEthernetManager$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return JEthernetManager$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $JEthernetManager$Companion$NullableType$
    extends jni$_.JType<JEthernetManager$Companion?> {
  @jni$_.internal
  const $JEthernetManager$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$Companion;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : JEthernetManager$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$Companion$NullableType$) &&
        other is $JEthernetManager$Companion$NullableType$;
  }
}

final class $JEthernetManager$Companion$Type$
    extends jni$_.JType<JEthernetManager$Companion> {
  @jni$_.internal
  const $JEthernetManager$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$Companion;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$Companion fromReference(jni$_.JReference reference) =>
      JEthernetManager$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$Companion?> get nullableType =>
      const $JEthernetManager$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$Companion$Type$) &&
        other is $JEthernetManager$Companion$Type$;
  }
}

/// from: `dev.zeekr.connectivity.ethernet.JEthernetManager$JListener`
class JEthernetManager$JListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JEthernetManager$JListener> $type;

  @jni$_.internal
  JEthernetManager$JListener.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/ethernet/JEthernetManager$JListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$JListener?> nullableType =
      $JEthernetManager$JListener$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$JListener> type =
      $JEthernetManager$JListener$Type$();
  static final _id_onAvailabilityChanged = _class.instanceMethodId(
    r'onAvailabilityChanged',
    r'(Ljava/lang/String;Z)V',
  );

  static final _onAvailabilityChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun onAvailabilityChanged(iface: kotlin.String, isAvailable: kotlin.Boolean): kotlin.Unit`
  void onAvailabilityChanged(jni$_.JString string, bool z) {
    final _$string = string.reference;
    _onAvailabilityChanged(
      reference.pointer,
      _id_onAvailabilityChanged as jni$_.JMethodIDPtr,
      _$string.pointer,
      z ? 1 : 0,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $JEthernetManager$JListener> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onAvailabilityChanged(Ljava/lang/String;Z)V') {
        _$impls[$p]!.onAvailabilityChanged(
          $a![0]!.as(const jni$_.$JString$Type$(), releaseOriginal: true),
          $a![1]!
              .as(const jni$_.$JBoolean$Type$(), releaseOriginal: true)
              .booleanValue(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $JEthernetManager$JListener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'dev.zeekr.connectivity.ethernet.JEthernetManager$JListener',
      $p,
      _$invokePointer,
      [
        if ($impl.onAvailabilityChanged$async)
          r'onAvailabilityChanged(Ljava/lang/String;Z)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory JEthernetManager$JListener.implement(
    $JEthernetManager$JListener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return JEthernetManager$JListener.fromReference($i.implementReference());
  }
}

abstract base mixin class $JEthernetManager$JListener {
  factory $JEthernetManager$JListener({
    required void Function(jni$_.JString string, bool z) onAvailabilityChanged,
    bool onAvailabilityChanged$async,
  }) = _$JEthernetManager$JListener;

  void onAvailabilityChanged(jni$_.JString string, bool z);
  bool get onAvailabilityChanged$async => false;
}

final class _$JEthernetManager$JListener with $JEthernetManager$JListener {
  _$JEthernetManager$JListener({
    required void Function(jni$_.JString string, bool z) onAvailabilityChanged,
    this.onAvailabilityChanged$async = false,
  }) : _onAvailabilityChanged = onAvailabilityChanged;

  final void Function(jni$_.JString string, bool z) _onAvailabilityChanged;
  final bool onAvailabilityChanged$async;

  void onAvailabilityChanged(jni$_.JString string, bool z) {
    return _onAvailabilityChanged(string, z);
  }
}

final class $JEthernetManager$JListener$NullableType$
    extends jni$_.JType<JEthernetManager$JListener?> {
  @jni$_.internal
  const $JEthernetManager$JListener$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListener;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$JListener? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : JEthernetManager$JListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$JListener?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$JListener$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$JListener$NullableType$) &&
        other is $JEthernetManager$JListener$NullableType$;
  }
}

final class $JEthernetManager$JListener$Type$
    extends jni$_.JType<JEthernetManager$JListener> {
  @jni$_.internal
  const $JEthernetManager$JListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListener;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$JListener fromReference(jni$_.JReference reference) =>
      JEthernetManager$JListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$JListener?> get nullableType =>
      const $JEthernetManager$JListener$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$JListener$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$JListener$Type$) &&
        other is $JEthernetManager$JListener$Type$;
  }
}

/// from: `dev.zeekr.connectivity.ethernet.JEthernetManager$JListenerImpl$Companion`
class JEthernetManager$JListenerImpl$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JEthernetManager$JListenerImpl$Companion> $type;

  @jni$_.internal
  JEthernetManager$JListenerImpl$Companion.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$JListenerImpl$Companion?>
  nullableType = $JEthernetManager$JListenerImpl$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$JListenerImpl$Companion> type =
      $JEthernetManager$JListenerImpl$Companion$Type$();
  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<?> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JEthernetManager$JListenerImpl$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return JEthernetManager$JListenerImpl$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $JEthernetManager$JListenerImpl$Companion$NullableType$
    extends jni$_.JType<JEthernetManager$JListenerImpl$Companion?> {
  @jni$_.internal
  const $JEthernetManager$JListenerImpl$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl$Companion;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$JListenerImpl$Companion? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : JEthernetManager$JListenerImpl$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$JListenerImpl$Companion?> get nullableType =>
      this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($JEthernetManager$JListenerImpl$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JEthernetManager$JListenerImpl$Companion$NullableType$) &&
        other is $JEthernetManager$JListenerImpl$Companion$NullableType$;
  }
}

final class $JEthernetManager$JListenerImpl$Companion$Type$
    extends jni$_.JType<JEthernetManager$JListenerImpl$Companion> {
  @jni$_.internal
  const $JEthernetManager$JListenerImpl$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl$Companion;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$JListenerImpl$Companion fromReference(
    jni$_.JReference reference,
  ) => JEthernetManager$JListenerImpl$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$JListenerImpl$Companion?> get nullableType =>
      const $JEthernetManager$JListenerImpl$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($JEthernetManager$JListenerImpl$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JEthernetManager$JListenerImpl$Companion$Type$) &&
        other is $JEthernetManager$JListenerImpl$Companion$Type$;
  }
}

/// from: `dev.zeekr.connectivity.ethernet.JEthernetManager$JListenerImpl`
class JEthernetManager$JListenerImpl extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JEthernetManager$JListenerImpl> $type;

  @jni$_.internal
  JEthernetManager$JListenerImpl.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$JListenerImpl?> nullableType =
      $JEthernetManager$JListenerImpl$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager$JListenerImpl> type =
      $JEthernetManager$JListenerImpl$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl$Companion;',
  );

  /// from: `static public final dev.zeekr.connectivity.ethernet.JEthernetManager$JListenerImpl$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static JEthernetManager$JListenerImpl$Companion get Companion => _id_Companion
      .get(_class, const $JEthernetManager$JListenerImpl$Companion$Type$());

  static final _id_new$ = _class.constructorId(
    r'(Landroid/content/Context;Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListener;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context, dev.zeekr.connectivity.ethernet.JEthernetManager$JListener jListener)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JEthernetManager$JListenerImpl(
    context$_.Context context,
    JEthernetManager$JListener jListener,
  ) {
    final _$context = context.reference;
    final _$jListener = jListener.reference;
    return JEthernetManager$JListenerImpl.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
        _$jListener.pointer,
      ).reference,
    );
  }

  static final _id_getObj = _class.instanceMethodId(
    r'getObj',
    r'()Ljava/lang/Object;',
  );

  static final _getObj =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Object getObj()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getObj() {
    return _getObj(
      reference.pointer,
      _id_getObj as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }
}

final class $JEthernetManager$JListenerImpl$NullableType$
    extends jni$_.JType<JEthernetManager$JListenerImpl?> {
  @jni$_.internal
  const $JEthernetManager$JListenerImpl$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$JListenerImpl? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : JEthernetManager$JListenerImpl.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$JListenerImpl?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$JListenerImpl$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JEthernetManager$JListenerImpl$NullableType$) &&
        other is $JEthernetManager$JListenerImpl$NullableType$;
  }
}

final class $JEthernetManager$JListenerImpl$Type$
    extends jni$_.JType<JEthernetManager$JListenerImpl> {
  @jni$_.internal
  const $JEthernetManager$JListenerImpl$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl;';

  @jni$_.internal
  @core$_.override
  JEthernetManager$JListenerImpl fromReference(jni$_.JReference reference) =>
      JEthernetManager$JListenerImpl.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager$JListenerImpl?> get nullableType =>
      const $JEthernetManager$JListenerImpl$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$JListenerImpl$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$JListenerImpl$Type$) &&
        other is $JEthernetManager$JListenerImpl$Type$;
  }
}

/// from: `dev.zeekr.connectivity.ethernet.JEthernetManager`
class JEthernetManager extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JEthernetManager> $type;

  @jni$_.internal
  JEthernetManager.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/ethernet/JEthernetManager',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager?> nullableType =
      $JEthernetManager$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JEthernetManager> type = $JEthernetManager$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/connectivity/ethernet/JEthernetManager$Companion;',
  );

  /// from: `static public final dev.zeekr.connectivity.ethernet.JEthernetManager$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static JEthernetManager$Companion get Companion =>
      _id_Companion.get(_class, const $JEthernetManager$Companion$Type$());

  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JEthernetManager(context$_.Context context) {
    final _$context = context.reference;
    return JEthernetManager.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_getObj = _class.instanceMethodId(
    r'getObj',
    r'()Ljava/lang/Object;',
  );

  static final _getObj =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Object getObj()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getObj() {
    return _getObj(
      reference.pointer,
      _id_getObj as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_isAvailable = _class.instanceMethodId(
    r'isAvailable',
    r'()Z',
  );

  static final _isAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final boolean isAvailable()`
  bool isAvailable() {
    return _isAvailable(
      reference.pointer,
      _id_isAvailable as jni$_.JMethodIDPtr,
    ).boolean;
  }

  static final _id_getAvailableInterfaces = _class.instanceMethodId(
    r'getAvailableInterfaces',
    r'()[Ljava/lang/String;',
  );

  static final _getAvailableInterfaces =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String[] getAvailableInterfaces()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<jni$_.JString> getAvailableInterfaces() {
    return _getAvailableInterfaces(
      reference.pointer,
      _id_getAvailableInterfaces as jni$_.JMethodIDPtr,
    ).object<jni$_.JArray<jni$_.JString>>(
      const jni$_.$JArray$Type$<jni$_.JString>(jni$_.$JString$Type$()),
    );
  }

  static final _id_getConfiguration = _class.instanceMethodId(
    r'getConfiguration',
    r'(Ljava/lang/String;)Ldev/zeekr/connectivity/JIpConfiguration;',
  );

  static final _getConfiguration =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getConfiguration(iface: kotlin.String): dev.zeekr.connectivity.JIpConfiguration`
  /// The returned object must be released after use, by calling the [release] method.
  jipconfiguration$_.JIpConfiguration getConfiguration(jni$_.JString string) {
    final _$string = string.reference;
    return _getConfiguration(
      reference.pointer,
      _id_getConfiguration as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jipconfiguration$_.JIpConfiguration>(
      const jipconfiguration$_.$JIpConfiguration$Type$(),
    );
  }

  static final _id_setConfiguration = _class.instanceMethodId(
    r'setConfiguration',
    r'(Ljava/lang/String;Ldev/zeekr/connectivity/JIpConfiguration;)V',
  );

  static final _setConfiguration =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setConfiguration(iface: kotlin.String, config: dev.zeekr.connectivity.JIpConfiguration): kotlin.Unit`
  void setConfiguration(
    jni$_.JString string,
    jipconfiguration$_.JIpConfiguration jIpConfiguration,
  ) {
    final _$string = string.reference;
    final _$jIpConfiguration = jIpConfiguration.reference;
    _setConfiguration(
      reference.pointer,
      _id_setConfiguration as jni$_.JMethodIDPtr,
      _$string.pointer,
      _$jIpConfiguration.pointer,
    ).check();
  }

  static final _id_isAvailable$1 = _class.instanceMethodId(
    r'isAvailable',
    r'(Ljava/lang/String;)Z',
  );

  static final _isAvailable$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun isAvailable(iface: kotlin.String): kotlin.Boolean`
  bool isAvailable$1(jni$_.JString string) {
    final _$string = string.reference;
    return _isAvailable$1(
      reference.pointer,
      _id_isAvailable$1 as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).boolean;
  }

  static final _id_addListener = _class.instanceMethodId(
    r'addListener',
    r'(Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl;)V',
  );

  static final _addListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun addListener(listener: dev.zeekr.connectivity.ethernet.JEthernetManager.JListenerImpl): kotlin.Unit`
  void addListener(JEthernetManager$JListenerImpl jListenerImpl) {
    final _$jListenerImpl = jListenerImpl.reference;
    _addListener(
      reference.pointer,
      _id_addListener as jni$_.JMethodIDPtr,
      _$jListenerImpl.pointer,
    ).check();
  }

  static final _id_removeListener = _class.instanceMethodId(
    r'removeListener',
    r'(Ldev/zeekr/connectivity/ethernet/JEthernetManager$JListenerImpl;)V',
  );

  static final _removeListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun removeListener(listener: dev.zeekr.connectivity.ethernet.JEthernetManager.JListenerImpl): kotlin.Unit`
  void removeListener(JEthernetManager$JListenerImpl jListenerImpl) {
    final _$jListenerImpl = jListenerImpl.reference;
    _removeListener(
      reference.pointer,
      _id_removeListener as jni$_.JMethodIDPtr,
      _$jListenerImpl.pointer,
    ).check();
  }
}

final class $JEthernetManager$NullableType$
    extends jni$_.JType<JEthernetManager?> {
  @jni$_.internal
  const $JEthernetManager$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/zeekr/connectivity/ethernet/JEthernetManager;';

  @jni$_.internal
  @core$_.override
  JEthernetManager? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : JEthernetManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$NullableType$) &&
        other is $JEthernetManager$NullableType$;
  }
}

final class $JEthernetManager$Type$ extends jni$_.JType<JEthernetManager> {
  @jni$_.internal
  const $JEthernetManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/zeekr/connectivity/ethernet/JEthernetManager;';

  @jni$_.internal
  @core$_.override
  JEthernetManager fromReference(jni$_.JReference reference) =>
      JEthernetManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JEthernetManager?> get nullableType =>
      const $JEthernetManager$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JEthernetManager$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JEthernetManager$Type$) &&
        other is $JEthernetManager$Type$;
  }
}
