// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/content/Context.dart' as context$_;

import '../../../android/content/Intent.dart' as intent$_;

/// from: `dev.zeekr.connectivity.JBroadcastReceiver`
class JBroadcastReceiver extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JBroadcastReceiver> $type;

  @jni$_.internal
  JBroadcastReceiver.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/JBroadcastReceiver',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JBroadcastReceiver?> nullableType =
      $JBroadcastReceiver$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JBroadcastReceiver> type =
      $JBroadcastReceiver$Type$();
  static final _id_onReceive = _class.instanceMethodId(
    r'onReceive',
    r'(Landroid/content/Context;Landroid/content/Intent;)V',
  );

  static final _onReceive =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onReceive(context: android.content.Context, intent: android.content.Intent): kotlin.Unit`
  void onReceive(context$_.Context context, intent$_.Intent intent) {
    final _$context = context.reference;
    final _$intent = intent.reference;
    _onReceive(
      reference.pointer,
      _id_onReceive as jni$_.JMethodIDPtr,
      _$context.pointer,
      _$intent.pointer,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $JBroadcastReceiver> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d ==
          r'onReceive(Landroid/content/Context;Landroid/content/Intent;)V') {
        _$impls[$p]!.onReceive(
          $a![0]!.as(const context$_.$Context$Type$(), releaseOriginal: true),
          $a![1]!.as(const intent$_.$Intent$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $JBroadcastReceiver $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'dev.zeekr.connectivity.JBroadcastReceiver',
      $p,
      _$invokePointer,
      [
        if ($impl.onReceive$async)
          r'onReceive(Landroid/content/Context;Landroid/content/Intent;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory JBroadcastReceiver.implement($JBroadcastReceiver $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return JBroadcastReceiver.fromReference($i.implementReference());
  }
}

abstract base mixin class $JBroadcastReceiver {
  factory $JBroadcastReceiver({
    required void Function(context$_.Context context, intent$_.Intent intent)
    onReceive,
    bool onReceive$async,
  }) = _$JBroadcastReceiver;

  void onReceive(context$_.Context context, intent$_.Intent intent);
  bool get onReceive$async => false;
}

final class _$JBroadcastReceiver with $JBroadcastReceiver {
  _$JBroadcastReceiver({
    required void Function(context$_.Context context, intent$_.Intent intent)
    onReceive,
    this.onReceive$async = false,
  }) : _onReceive = onReceive;

  final void Function(context$_.Context context, intent$_.Intent intent)
  _onReceive;
  final bool onReceive$async;

  void onReceive(context$_.Context context, intent$_.Intent intent) {
    return _onReceive(context, intent);
  }
}

final class $JBroadcastReceiver$NullableType$
    extends jni$_.JType<JBroadcastReceiver?> {
  @jni$_.internal
  const $JBroadcastReceiver$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/zeekr/connectivity/JBroadcastReceiver;';

  @jni$_.internal
  @core$_.override
  JBroadcastReceiver? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : JBroadcastReceiver.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JBroadcastReceiver?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JBroadcastReceiver$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JBroadcastReceiver$NullableType$) &&
        other is $JBroadcastReceiver$NullableType$;
  }
}

final class $JBroadcastReceiver$Type$ extends jni$_.JType<JBroadcastReceiver> {
  @jni$_.internal
  const $JBroadcastReceiver$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/zeekr/connectivity/JBroadcastReceiver;';

  @jni$_.internal
  @core$_.override
  JBroadcastReceiver fromReference(jni$_.JReference reference) =>
      JBroadcastReceiver.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JBroadcastReceiver?> get nullableType =>
      const $JBroadcastReceiver$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JBroadcastReceiver$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JBroadcastReceiver$Type$) &&
        other is $JBroadcastReceiver$Type$;
  }
}
