// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/net/LinkAddress.dart' as linkaddress$_;

import '../../../android/net/LinkProperties.dart' as linkproperties$_;

import '../../../android/net/RouteInfo.dart' as routeinfo$_;

import '../../../java/net/InetAddress.dart' as inetaddress$_;

/// from: `dev.zeekr.connectivity.JStaticIpConfiguration$Companion`
class JStaticIpConfiguration$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JStaticIpConfiguration$Companion> $type;

  @jni$_.internal
  JStaticIpConfiguration$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/JStaticIpConfiguration$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JStaticIpConfiguration$Companion?> nullableType =
      $JStaticIpConfiguration$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JStaticIpConfiguration$Companion> type =
      $JStaticIpConfiguration$Companion$Type$();
  static final _id_getClazz = _class.instanceMethodId(
    r'getClazz',
    r'()Ljava/lang/Class;',
  );

  static final _getClazz =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Class<?> getClazz()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getClazz() {
    return _getClazz(
      reference.pointer,
      _id_getClazz as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JStaticIpConfiguration$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return JStaticIpConfiguration$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $JStaticIpConfiguration$Companion$NullableType$
    extends jni$_.JType<JStaticIpConfiguration$Companion?> {
  @jni$_.internal
  const $JStaticIpConfiguration$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/JStaticIpConfiguration$Companion;';

  @jni$_.internal
  @core$_.override
  JStaticIpConfiguration$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : JStaticIpConfiguration$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JStaticIpConfiguration$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($JStaticIpConfiguration$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JStaticIpConfiguration$Companion$NullableType$) &&
        other is $JStaticIpConfiguration$Companion$NullableType$;
  }
}

final class $JStaticIpConfiguration$Companion$Type$
    extends jni$_.JType<JStaticIpConfiguration$Companion> {
  @jni$_.internal
  const $JStaticIpConfiguration$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity/JStaticIpConfiguration$Companion;';

  @jni$_.internal
  @core$_.override
  JStaticIpConfiguration$Companion fromReference(jni$_.JReference reference) =>
      JStaticIpConfiguration$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JStaticIpConfiguration$Companion?> get nullableType =>
      const $JStaticIpConfiguration$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JStaticIpConfiguration$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JStaticIpConfiguration$Companion$Type$) &&
        other is $JStaticIpConfiguration$Companion$Type$;
  }
}

/// from: `dev.zeekr.connectivity.JStaticIpConfiguration`
class JStaticIpConfiguration extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JStaticIpConfiguration> $type;

  @jni$_.internal
  JStaticIpConfiguration.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity/JStaticIpConfiguration',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JStaticIpConfiguration?> nullableType =
      $JStaticIpConfiguration$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JStaticIpConfiguration> type =
      $JStaticIpConfiguration$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/zeekr/connectivity/JStaticIpConfiguration$Companion;',
  );

  /// from: `static public final dev.zeekr.connectivity.JStaticIpConfiguration$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static JStaticIpConfiguration$Companion get Companion => _id_Companion.get(
    _class,
    const $JStaticIpConfiguration$Companion$Type$(),
  );

  static final _id_new$ = _class.constructorId(r'(Ljava/lang/Object;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JStaticIpConfiguration(jni$_.JObject object) {
    final _$object = object.reference;
    return JStaticIpConfiguration.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$object.pointer,
      ).reference,
    );
  }

  static final _id_getObj = _class.instanceMethodId(
    r'getObj',
    r'()Ljava/lang/Object;',
  );

  static final _getObj =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Object getObj()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getObj() {
    return _getObj(
      reference.pointer,
      _id_getObj as jni$_.JMethodIDPtr,
    ).object<jni$_.JObject>(const jni$_.$JObject$Type$());
  }

  static final _id_clear = _class.instanceMethodId(r'clear', r'()V');

  static final _clear =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun clear(): kotlin.Unit`
  void clear() {
    _clear(reference.pointer, _id_clear as jni$_.JMethodIDPtr).check();
  }

  static final _id_getIpAddress = _class.instanceMethodId(
    r'getIpAddress',
    r'()Landroid/net/LinkAddress;',
  );

  static final _getIpAddress =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final android.net.LinkAddress getIpAddress()`
  /// The returned object must be released after use, by calling the [release] method.
  linkaddress$_.LinkAddress getIpAddress() {
    return _getIpAddress(
      reference.pointer,
      _id_getIpAddress as jni$_.JMethodIDPtr,
    ).object<linkaddress$_.LinkAddress>(
      const linkaddress$_.$LinkAddress$Type$(),
    );
  }

  static final _id_getGateway = _class.instanceMethodId(
    r'getGateway',
    r'()Ljava/net/InetAddress;',
  );

  static final _getGateway =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.net.InetAddress getGateway()`
  /// The returned object must be released after use, by calling the [release] method.
  inetaddress$_.InetAddress getGateway() {
    return _getGateway(
      reference.pointer,
      _id_getGateway as jni$_.JMethodIDPtr,
    ).object<inetaddress$_.InetAddress>(
      const inetaddress$_.$InetAddress$Type$(),
    );
  }

  static final _id_getDnsServers = _class.instanceMethodId(
    r'getDnsServers',
    r'()Ljava/util/List;',
  );

  static final _getDnsServers =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.util.List<java.net.InetAddress> getDnsServers()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<inetaddress$_.InetAddress> getDnsServers() {
    return _getDnsServers(
      reference.pointer,
      _id_getDnsServers as jni$_.JMethodIDPtr,
    ).object<jni$_.JList<inetaddress$_.InetAddress>>(
      const jni$_.$JList$Type$<inetaddress$_.InetAddress>(
        inetaddress$_.$InetAddress$Type$(),
      ),
    );
  }

  static final _id_getDomains = _class.instanceMethodId(
    r'getDomains',
    r'()Ljava/lang/String;',
  );

  static final _getDomains =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.String getDomains()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getDomains() {
    return _getDomains(
      reference.pointer,
      _id_getDomains as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_addDnsServer = _class.instanceMethodId(
    r'addDnsServer',
    r'(Ljava/net/InetAddress;)V',
  );

  static final _addDnsServer =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun addDnsServer(server: java.net.InetAddress): kotlin.Unit`
  void addDnsServer(inetaddress$_.InetAddress inetAddress) {
    final _$inetAddress = inetAddress.reference;
    _addDnsServer(
      reference.pointer,
      _id_addDnsServer as jni$_.JMethodIDPtr,
      _$inetAddress.pointer,
    ).check();
  }

  static final _id_getRoutes = _class.instanceMethodId(
    r'getRoutes',
    r'(Ljava/lang/String;)Ljava/util/List;',
  );

  static final _getRoutes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun getRoutes(iface: kotlin.String?): kotlin.collections.List<android.net.RouteInfo>`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<routeinfo$_.RouteInfo> getRoutes(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getRoutes(
      reference.pointer,
      _id_getRoutes as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<jni$_.JList<routeinfo$_.RouteInfo>>(
      const jni$_.$JList$Type$<routeinfo$_.RouteInfo>(
        routeinfo$_.$RouteInfo$Type$(),
      ),
    );
  }

  static final _id_toLinkProperties = _class.instanceMethodId(
    r'toLinkProperties',
    r'(Ljava/lang/String;)Landroid/net/LinkProperties;',
  );

  static final _toLinkProperties =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun toLinkProperties(iface: kotlin.String?): android.net.LinkProperties`
  /// The returned object must be released after use, by calling the [release] method.
  linkproperties$_.LinkProperties toLinkProperties(jni$_.JString? string) {
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _toLinkProperties(
      reference.pointer,
      _id_toLinkProperties as jni$_.JMethodIDPtr,
      _$string.pointer,
    ).object<linkproperties$_.LinkProperties>(
      const linkproperties$_.$LinkProperties$Type$(),
    );
  }
}

final class $JStaticIpConfiguration$NullableType$
    extends jni$_.JType<JStaticIpConfiguration?> {
  @jni$_.internal
  const $JStaticIpConfiguration$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/zeekr/connectivity/JStaticIpConfiguration;';

  @jni$_.internal
  @core$_.override
  JStaticIpConfiguration? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : JStaticIpConfiguration.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JStaticIpConfiguration?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JStaticIpConfiguration$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JStaticIpConfiguration$NullableType$) &&
        other is $JStaticIpConfiguration$NullableType$;
  }
}

final class $JStaticIpConfiguration$Type$
    extends jni$_.JType<JStaticIpConfiguration> {
  @jni$_.internal
  const $JStaticIpConfiguration$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ldev/zeekr/connectivity/JStaticIpConfiguration;';

  @jni$_.internal
  @core$_.override
  JStaticIpConfiguration fromReference(jni$_.JReference reference) =>
      JStaticIpConfiguration.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JStaticIpConfiguration?> get nullableType =>
      const $JStaticIpConfiguration$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JStaticIpConfiguration$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JStaticIpConfiguration$Type$) &&
        other is $JStaticIpConfiguration$Type$;
  }
}
